import datetime
now=datetime.datetime.now()

def card(deg):
    file=str(deg)+'\MsNB.inp'
    f = open(file, 'w')
    f.write('Molten Salt Nuclear Battery with Control Drums ')
    f.write(str(deg))
    f.write(' degrees\n')
    f.write('c      -----------------------------------------------------------------\n')
    f.write('c      S.J.Root\n')
    f.write('c      -----------------------------------------------------------------\n')
    f.write('c      ')
    f.write(now.strftime("%d.%b.%Y"))
    f.write( '\n')
    f.write('c      -----------------------------------------------------------------\n')
    f.write('c      \n')
    f.write('c      ------------------------- MODEL NOTES ---------------------------\n')
    f.write('c      \n')
    f.write('c      This is a model that is used to calculate the criticality of the MsNB\n')
    f.write('c      based on the control drum orientation\n')
    f.write('c      Current Orientation: ')
    f.write(str(deg))
    f.write(' degrees\n')
    f.write('c      \n')
    f.write('c      ----------------------- END MODEL NOTES -------------------------\n')
    f.write('c      \n')
    f.write('c      -----------------------------------------------------------------\n')
    f.write('c      \n')
    f.write('c      ------------------------- START CARDS ---------------------------\n')
    f.write('c      \n')
    f.close()
