import rotate

def card(deg):
    file=str(deg)+'\MsNB.inp'
    f = open(file, 'a')
    f.write('\n')
    f.write('c      -----------\n')
    f.write('c      surface cards\n')
    f.write('c      -----------\n')
    f.write("10     CZ   24.0     $CorePipe Inner\n")
    f.write('c      ---\n')
    f.write("11     CZ   25.0     $CorePipe Outer\n")
    f.write('c      ---\n')
    f.write("12     CZ   73.5     $Shroud Liner Inner\n")
    f.write('c      ---\n')
    f.write("13     CZ   74.0     $Shroud Inner\n")
    f.write('c      ---\n')
    f.write("14     CZ   75.0     $Shroud Outer\n")
    f.write('c      ---\n')
    f.write("20     PZ  -110.0    $Shroud Bottom\n")
    f.write('c      ---\n')
    f.write("21     PZ   110.0    $Shroud Top\n")
    f.write('c      ---\n')
    f.write("22     PZ  -83.0     $Core Bottom\n")
    f.write('c      ---\n')
    f.write("23     PZ   83.0     $Core Top\n")
    f.write('c      ---\n')
    f.write("24     PZ   83.5     $Cap Top\n")
    f.write('c      ---\n')
    f.write("25     PZ  -83.5     $Plug bottom\n")
    f.write('c      ---\n')
    f.write("26     PZ  -109.0    $Shroud Tray Top\n")
    f.write('c      ---\n')
    f.write("27     PZ   109.0    $Shroud Lid Bottom\n")
    f.write('c      ---\n')
    f.write("30     C/Z  0 49.5 19.5    $12 o'clock inner\n")
    f.write('c      ---\n')
    f.write("31     C/Z  0 49.5 20.0    $12 o'clock outer\n")
    f.write('c      ---\n')
    f.write('32     P    ')
    f.write(rotate.drum(deg,12))
    f.write("$12 o'clock bisector\n")
    f.write('c      ---\n')
    f.write("40     C/Z  42.9 24.7 19.5      $2 o'clock inner\n")
    f.write('c      ---\n')
    f.write("41     C/Z  42.9 24.7 20.0      $2 o'clock out\n")
    f.write('c      ---\n')
    f.write('42     P    ')
    f.write(rotate.drum(deg,2))
    f.write("$2 o'clock bisector\n")
    f.write('c      ---\n')
    f.write("50     C/Z  42.9 -24.7 19.5      $4 o'clock inner\n")
    f.write('c      ---\n')
    f.write("51     C/Z  42.9 -24.7 20.0      $4 o'clock out\n")
    f.write('c      ---\n')
    f.write('52     P    ')
    f.write(rotate.drum(deg,4))
    f.write("$4 o'clock bisector\n")
    f.write('c      ---\n')
    f.write("60     C/Z  0 -49.5 19.5   $6 o'clock inner\n")
    f.write('c      ---\n')
    f.write("61     C/Z  0 -49.5 20.0   $6 o'clock out\n")
    f.write('c      ---\n')
    f.write('62     P    ')
    f.write(rotate.drum(deg,6))
    f.write("$6 o'clock bisector\n")
    f.write('c      ---\n')
    f.write("70     C/Z  -42.9 -24.7 19.5      $8 o'clock inner\n")
    f.write('c      ---\n')
    f.write("71     C/Z  -42.9 -24.7 20.0      $8 o'clock out\n")
    f.write('c      ---\n')
    f.write('72     P    ')
    f.write(rotate.drum(deg,8))
    f.write("$8 o'clock bisector\n")
    f.write('c      ---\n')
    f.write("80     C/Z  -42.9 24.7 19.5      $10 o'clock inner\n")
    f.write('c      ---\n')
    f.write("81     C/Z  -42.9 24.7 20.0      $10 o'clock out\n")
    f.write('c      ---\n')
    f.write('82     P    ')
    f.write(rotate.drum(deg,10))
    f.write("$10 o'clock bisector\n")
    f.write('c      ---\n')
    f.write('c      -----------\n')
    f.write('c      end surface cards\n')
    f.write('c      -----------\n')
    f.close()
